### ISSUE TITLE
bug: tap-recruitee install fails

### ISSUE THREAD

**Issue by pnadolny13** [meltano/hub#989]
https://hub.meltano.com/extractors/tap-recruitee

```
Traceback (most recent call last):
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/extractors/tap-recruitee/venv/bin/tap-recruitee", line 5, in <module>
    from tap_recruitee import main
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/extractors/tap-recruitee/venv/lib/python3.8/site-packages/tap_recruitee/__init__.py", line 1, in <module>
    import singer
ModuleNotFoundError: No module named 'singer'
```

**Comment by edgarrmondragon** [comment]
@pnadolny13 The `setup.py` file [is doing some unorthodox stuff](https://github.com/Tahasadiki/tap-recruitee/blob/3fbbf7b2baf37240223bad1e6644bc05b329dbbf/setup.py) by suggesting it be edited locally when installing the tap (as non-editable) so dependencies are actually installed along-side...

A workaround on our side might be to update our `pip_url` to include those packages:

```yaml
pip_url: >
  git+https://github.com/Tahasadiki/tap-recruitee.git
  attrs==18.1.0
  backoff==1.3.2
  python-dateutil==2.7.3
  requests==2.20.0
  singer-python==5.3.3
```
